### ISSUE TITLE
 com.google.android.things.pio.PioException: android.os.ServiceSpecificException: I/O error (code 5)

### ISSUE THREAD

**Issue by avatar21** [cagdasc/AndroidThings-HMC5883L#1]
Hi Cagdasc,

I'm testing your driver sample for HMC5883L on Raspberry Pi 3 running Android Things
Not sure am I plugging in wrongly or what?

I'm following this [guide](http://www.instructables.com/id/Interfacing-Digital-Compass-HMC5883L-with-Raspberr/) for the pins layout ... which is 
VCC => RED => pin #1
GND => BLACK => pin #6
SDA => WHITE => pin #3
SCL => GREY => pin #5
Then I got following exception trace when I run the sample.

```
E/MagnetometerActivity: Error configuring sensor
                        com.google.android.things.pio.PioException: android.os.ServiceSpecificException: I/O error (code 5)
                            at com.google.android.things.pio.I2cDeviceImpl.readRegByte(I2cDeviceImpl.java:81)
                            at com.cacaosd.hmc5883l.HMC5883L.setSamplesAvarage(HMC5883L.java:122)
                            at com.cacaosd.hmc5883l.HMC5883L.connect(HMC5883L.java:114)
                            at com.cacaosd.hmc5883l.HMC5883L.<init>(HMC5883L.java:94)
                            at com.cacaosd.hmc5883l.HMC5883LSensorDriver.<init>(HMC5883LSensorDriver.java:50)
                            at com.cacaosd.hmc5885lsample.MagnetometerActivity.onCreate(MagnetometerActivity.java:55)
                            at android.app.Activity.performCreate(Activity.java:6975)
```
Wondering what I did wrong.

**Comment by avatar21** [comment]
Working now ... it could be my pins setup issue ...
Here's a revise of my previous pin layout for i2c1 bus

VCC => RED => pin #1 (3.3v DC Power)
GND => BLACK => pin #6 
SCL => GREY => pin #5
SDA => WHITE => pin #3

And i2c0 bus (tested working with python3 code with Raspbian rpi2, but not sure how to enable i2c0 on Android Things rpi3)

VCC => RED => pin #17 (3.3v DC Power)
GND => BLACK => pin #25
SCL => GREY => pin #28
SDA => WHITE => pin #27
